# Generated by Django 5.2.5 on 2025-08-26 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='shifts.shift'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='shifts.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftschedule',
            unique_together={('user', 'date')},
        ),
    ]
