# Generated by Django 5.2.5 on 2025-08-29 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='shifts.shift'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shift_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='shifts.shift'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='shifts.shifttemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftschedule',
            unique_together={('employee', 'date')},
        ),
    ]
