# Generated by Django 5.2.5 on 2025-08-29 10:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('regular_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
