# Generated by Django 5.2.5 on 2025-09-27 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('shift', 'Shift'), ('system', 'System'), ('general', 'General'), ('message', 'Message')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('shift', 'Shift'), ('system', 'System'), ('general', 'General'), ('message', 'Message')], max_length=20),
        ),
    ]
