# Generated by Django 5.2.5 on 2025-09-13 14:48

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_recognition_enabled', models.BooleanField(default=True)),
                ('face_confidence_threshold', models.FloatField(default=0.6, help_text='Minimum confidence score for face recognition (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('location_tracking_enabled', models.BooleanField(default=False)),
                ('location_radius_meters', models.PositiveIntegerField(default=100, help_text='Allowed radius from office location in meters')),
                ('office_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('office_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('late_threshold_minutes', models.PositiveIntegerField(default=15, help_text='Minutes after shift start time to mark as late')),
                ('early_departure_threshold_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before shift end time to mark as early departure')),
                ('require_photo_for_attendance', models.BooleanField(default=False)),
                ('allow_manual_attendance', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
                'db_table': 'attendance_settings',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendance_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out')], max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('early_departure', 'Early Departure')], default='present', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('face_verified', models.BooleanField(default=False)),
                ('face_confidence', models.FloatField(blank=True, help_text='Face recognition confidence score (0.0 - 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='attendance/faces/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, help_text='Device information for audit trail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='attendance_user_id_d716c4_idx'), models.Index(fields=['date', 'attendance_type'], name='attendance_date_b077e2_idx'), models.Index(fields=['user', 'attendance_type', 'date'], name='attendance_user_id_bb7b7a_idx')],
            },
        ),
    ]
