# Generated by Django 5.2.5 on 2025-08-26 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('attendance_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out')], max_length=10)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('half_day', 'Half Day')], default='present', max_length=10)),
                ('face_verified', models.BooleanField(default=False)),
                ('face_confidence', models.FloatField(blank=True, help_text='Confidence score for face recognition', null=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('manual_reason', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
